import { useEffect, useMemo, useState } from 'react'
import { checkScholarshipEligibility, ensureScholarshipTasks, fetchOpenScholarships, fetchSavedScholarshipIds, fetchScholarshipApplications, fetchScholarshipTasks, setScholarshipTaskCompleted, toggleSavedScholarship, type Scholarship, type ScholarshipApplication, type ScholarshipTask } from '../lib/scholarships'
import { applyToOpportunity } from '../lib/opportunities'

const labels:Record<string,string>={submitted:'Submitted',under_review:'Under review',shortlisted:'Shortlisted',accepted:'Accepted',rejected:'Rejected',withdrawn:'Withdrawn'}

export default function EthioScholarConnect({onBack}:{onBack:()=>void}) {
 const [items,setItems]=useState<Scholarship[]>([]); const [saved,setSaved]=useState<Set<string>>(new Set()); const [apps,setApps]=useState<ScholarshipApplication[]>([]); const [tasks,setTasks]=useState<ScholarshipTask[]>([]); const [tab,setTab]=useState('discover'); const [search,setSearch]=useState(''); const [country,setCountry]=useState(''); const [selected,setSelected]=useState<Scholarship|null>(null); const [eligibility,setEligibility]=useState<any>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState<string|null>(null)
 const load=async()=>{try{const [a,b,c,d]=await Promise.all([fetchOpenScholarships(),fetchSavedScholarshipIds(),fetchScholarshipApplications(),fetchScholarshipTasks()]);setItems(a);setSaved(b);setApps(c);setTasks(d)}catch(e:any){setError(e.message||'Could not load scholarship center.')}}
 useEffect(()=>{load()},[])
 const countries=useMemo(()=>Array.from(new Set(items.map(x=>x.study_country).filter(Boolean))) as string[],[items])
 const filtered=useMemo(()=>items.filter(s=>(!search||[s.title,s.institution,s.program_name,...s.fields_of_study].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()))&&(!country||s.study_country===country)&&(tab!=='saved'||saved.has(s.id))),[items,search,country,tab,saved])
 const save=async(s:Scholarship)=>{setBusy(s.id);try{const was=saved.has(s.id);await toggleSavedScholarship(s.id,was);setSaved(old=>{const n=new Set(old);was?n.delete(s.id):n.add(s.id);return n})}catch(e:any){setError(e.message||'Could not save scholarship.')}finally{setBusy(null)}}
 const start=async(s:Scholarship)=>{setBusy(s.id);setError('');try{if(s.application_method==='external'){if(!s.external_url)throw new Error('No official application URL is available.');await ensureScholarshipTasks(s);window.open(s.external_url,'_blank','noopener,noreferrer')}else{await applyToOpportunity(s.id,'');const a=(await fetchScholarshipApplications()).find(x=>x.opportunity_id===s.id);await ensureScholarshipTasks(s,a?.id)}await load()}catch(e:any){setError(e.message||'Could not start application.')}finally{setBusy(null)}}
 const progress=(id:string)=>{const t=tasks.filter(x=>x.opportunity_id===id);return t.length?Math.round(t.filter(x=>x.completed).length/t.length*100):0}
 return <div className='dash-main'><div className='section-heading'><div><h1>Scholarship Center</h1><p className='muted'>Verified opportunities, eligibility information, requirements, preparation and application progress.</p></div><button className='btn btn-secondary' onClick={onBack}>Back</button></div>
 {error&&<div className='banner banner-error'>{error}</div>}
 <div className='list-panel'><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}><button className={tab==='discover'?'btn btn-primary':'btn btn-secondary'} onClick={()=>setTab('discover')}>Discover</button><button className={tab==='saved'?'btn btn-primary':'btn btn-secondary'} onClick={()=>setTab('saved')}>Saved ({saved.size})</button><button className={tab==='applications'?'btn btn-primary':'btn btn-secondary'} onClick={()=>setTab('applications')}>My Applications ({apps.length})</button></div>
 {tab!=='applications'&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}><input aria-label='Search scholarships' placeholder='Search scholarships' value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label='Study country' value={country} onChange={e=>setCountry(e.target.value)}><option value=''>All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select></div>}
 {tab==='applications'?<>{apps.length===0?<div className='empty-panel'>No applications yet. Start from Discover.</div>:apps.map(a=><div className='list-row' key={a.id}><div style={{flex:1}}><div className='list-row-title'>{a.title}</div><div className='list-row-meta'>{a.institution||'Scholarship'} · {labels[a.status]||a.status}</div><div className='muted'>Preparation progress: {progress(a.opportunity_id)}%</div><progress value={progress(a.opportunity_id)} max='100' style={{width:'100%'}}/></div></div>)}</>:filtered.length===0?<div className='empty-panel'>{tab==='saved'?'No saved scholarships yet.':'No verified open scholarships match your search.'}</div>:filtered.map(s=><div className='list-row' key={s.id}><div style={{flex:1}}><div className='list-row-title'>{s.title}</div><div className='list-row-meta'>{s.institution||'Scholarship'} · {s.study_country||'Global'} · {s.funding_type||'Funding unspecified'}{s.deadline?' · Due '+s.deadline:''}</div><div className='list-row-meta'>{s.required_documents.length} requirements{s.verified_at?' · Verified '+new Date(s.verified_at).toLocaleDateString():''}</div></div><div style={{display:'flex',gap:8,alignItems:'center'}}><button className='btn btn-secondary' onClick={async()=>{setSelected(s);setEligibility(null);try{setEligibility(await checkScholarshipEligibility(s.id))}catch{}}}>Details</button><button className='btn btn-secondary' disabled={busy===s.id} onClick={()=>save(s)}>{saved.has(s.id)?'Saved':'Save'}</button><button className='btn btn-primary' disabled={busy===s.id} onClick={()=>start(s)}>{s.application_method==='external'?'Official site':'Start application'}</button></div></div>)}
 </div>
 {selected&&<div className='list-panel' style={{marginTop:16}}><div className='section-heading'><h2>{selected.title}</h2><button className='btn btn-secondary' onClick={()=>setSelected(null)}>Close</button></div><p>{selected.description}</p><p><strong>Eligibility:</strong> {eligibility?.eligible!==undefined?(eligibility.eligible?'Eligible based on current profile data.':'Not currently eligible based on current profile data.'):'Eligibility check available to premium users.'}</p><p><strong>Criteria:</strong> {selected.eligible_countries.join(', ')||'See official requirements'}{selected.minimum_gpa?' · Minimum GPA '+selected.minimum_gpa:''}</p><p><strong>Study level:</strong> {selected.degree_levels.join(', ')||'Not specified'}</p><p><strong>Fields:</strong> {selected.fields_of_study.join(', ')||'Not specified'}</p><p><strong>Documents:</strong> {selected.required_documents.join(', ')||'Not specified'}</p><p><strong>Coverage:</strong> {selected.coverage.join(', ')||'Not specified'}</p>{selected.source_url&&<p><a href={selected.source_url} target='_blank' rel='noopener noreferrer'>Official source</a></p>}<p className='muted'>External application progress is user-tracked unless MELA has a real provider integration; MELA never invents an external status.</p></div>}
 {tab==='applications'&&tasks.length>0&&<div className='list-panel' style={{marginTop:16}}><h2>Requirements checklist</h2>{tasks.map(t=><label className='list-row' key={t.id}><span><input type='checkbox' checked={t.completed} onChange={()=>setScholarshipTaskCompleted(t.id,!t.completed).then(load).catch((e:any)=>setError(e.message||'Could not update task.'))}/> {t.title}</span><span className='muted'>{t.due_at?'Due '+new Date(t.due_at).toLocaleDateString():''}</span></label>)}</div>}
 </div>
}