import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { fetchStudentServices, markNotificationRead } from '../lib/studentServices'
type Tab='scholarships'|'notifications'|'wallet'|'earn'|'challenges'|'applications'|'documents'|'progress'
export default function StudentServices({onBack}:{onBack:()=>void}){
 const [tab,setTab]=useState<Tab>('notifications'); const [data,setData]=useState<any>(null); const [error,setError]=useState('')
 const load=()=>fetchStudentServices().then(setData).catch(e=>setError(e.message??'Could not load data.')); useEffect(()=>{load()},[])
 if(error)return <main className="dash-main"><button className="btn btn-secondary" onClick={onBack}>← Back</button><div className="banner banner-error">{error}</div></main>
 if(!data)return <div className="centered-loading">Loading your MELA services…</div>
 const tabs:[Tab,string][]=[['scholarships','Scholarships'],['notifications','Notifications'],['wallet','Wallet'],['earn','Earn & Work'],['challenges','Challenges'],['applications','Applications'],['documents','Documents'],['progress','Progress & analytics']]
 return <main className="dash-main"><button className="btn btn-secondary" onClick={onBack}>← Dashboard</button><div className="section-heading"><h1>Student Services</h1></div><div className="module-grid">{tabs.map(([k,l])=><button key={k} className="module-card" onClick={()=>setTab(k)}><h3>{l}</h3><p>Live Supabase data</p></button>)}</div><section className="list-panel">
 {tab==='notifications'&&(data.notifications.length?data.notifications.map((n:any)=><div className="list-row" key={n.id}><div><b>{n.title}</b><div className="list-row-meta">{n.body}</div></div>{!n.is_read&&<button className="btn btn-secondary" onClick={()=>markNotificationRead(n.id).then(load)}>Mark read</button>}</div>):<Empty text="No notifications yet."/>)} 
 {tab==='wallet'&&(data.earnings.length?data.earnings.map((e:any)=><div className="list-row" key={e.id}><div><b>{e.source_type}</b><div className="list-row-meta">{e.status} · {e.occurred_at}</div></div><span className="pill">{e.net_amount} {e.currency}</span></div>):<Empty text="No earnings ledger entries yet."/>)} 
 {tab==='earn'&&(data.tasks.length?data.tasks.map((t:any)=><div className="list-row" key={t.id}><div><b>{t.title}</b><div className="list-row-meta">{t.task_type} · {t.status}</div></div><span className="pill">{t.budget_amount??t.reward_coins??0} {t.currency??'coins'}</span></div>):<Empty text="No work opportunities are currently visible."/>)} 
 {tab==='applications'&&(data.applications.length?data.applications.map((a:any)=><div className="list-row" key={a.id}><div><b>Application</b><div className="list-row-meta">{a.opportunity_id}</div></div><span className="pill">{a.status}</span></div>):<Empty text="You have not submitted applications yet."/>)} 
 {tab==='documents'&&(data.documents.length?data.documents.map((d:any)=><div className="list-row" key={d.id}><div><b>{d.title}</b><div className="list-row-meta">{d.document_type} · {d.issuer??'Self uploaded'}</div></div><span className="pill">{d.verified?'Verified':'Unverified'}</span></div>):<Empty text="No profile documents uploaded yet."/>)} 
 {tab==='challenges'&&(data.challenges.length?data.challenges.map((c:any)=><div className="list-row" key={c.challenge_id}><div><b>Challenge</b><div className="list-row-meta">{c.challenge_id} · {c.joined_at}</div></div><span className="pill">{c.status}</span></div>):<Empty text="No challenge participation recorded yet."/>)} 
 {tab==='progress'&&(data.progress.length?data.progress.map((p:any)=><div className="list-row" key={p.id}><div><b>Module {p.module_id}</b><div className="list-row-meta">{p.completed?'Completed':'In progress'} · quiz {p.quiz_score??0}</div></div><span className="pill">{p.proctored_passed?'Proctored ✓':'Not proctored'}</span></div>):<Empty text="No module progress recorded yet."/>)} 
 {tab==='scholarships'&&<Scholarships/>}
 </section></main>
}
function Empty({text}:{text:string}){return <div className="empty-panel">{text}</div>}
function Scholarships(){const [items,setItems]=useState<any[]|null>(null);const [err,setErr]=useState('');useEffect(()=>{supabase.from('scholarship_details').select('opportunity_id,institution,program_name,study_country,degree_levels,fields_of_study,funding_type,coverage,award_amount,award_currency,required_documents,source_verified_at').order('updated_at',{ascending:false}).limit(50).then(({data,error})=>{if(error)setErr(error.message);else setItems(data??[])})},[]);if(err)return <div className="banner banner-error">{err}</div>;if(!items)return <div className="centered-loading">Loading scholarships…</div>;return items.length?items.map(s=><div className="list-row" key={s.opportunity_id}><div><b>{s.program_name??'Scholarship opportunity'}</b><div className="list-row-meta">{s.institution??'Institution not listed'} · {s.study_country??'Country not listed'} · {s.funding_type??'Funding details available'}</div></div><span className="pill">{s.source_verified_at?'Source verified':'Verification pending'}</span></div>):<Empty text="No scholarship records are currently published."/>}
