export const COACH_MESSAGES={
 coachIntro:['Ask about a skill to focus on or how to prepare for your next opportunity.','ማሻሻል ስለሚፈልጉት ክህሎት ወይም ለቀጣዩ እድልዎ ስለመዘጋጀት ይጠይቁ።','Dandeettii irratti xiyyeeffachuu ykn carraa itti aanuuf qophaa’uu gaafadhaa.','ብዛዕባ ክተማዕብልዎ እትደልዩ ክእለት ወይ ንቀጻሊ ዕድል ምድላው ሕተቱ።','Weydii xirfad aad horumarinayso ama sida aad fursadda xigta ugu diyaargaroobayso.'],
 coachQuestion:['Question for your career coach','ለሙያ አማካሪዎ ጥያቄ','Gaaffii gorsaa hojii keessaniif','ሕቶ ንኣማኻሪ ሞያኹም','Su’aal loogu talagalay la taliyaha xirfadda'],
 coachPlaceholder:['Ask your career coach…','የሙያ አማካሪዎን ይጠይቁ…','Gorsaa hojii keessan gaafadhaa…','ኣማኻሪ ሞያኹም ሕተቱ…','Weydii la taliyaha xirfadda…'],
 coachSend:['Send','ላክ','Ergi','ስደድ','Dir'],
 coachThinking:['Thinking…','በማሰብ ላይ…','Yaadaa jira…','ይሓስብ ኣሎ…','Waa la fikirayaa…'],
 coachClear:['Clear conversation','ውይይቱን አጽዳ','Marii haqi','ዝርርብ ኣጽሪ','Tirtir wada hadalka'],
 coachHistoryHelp:['The last 40 messages and your draft stay in this tab for 30 minutes. Signing out clears them. AI advice is guidance, not a verified credential.','የመጨረሻዎቹ 40 መልዕክቶች እና ረቂቅዎ በዚህ ትር ለ30 ደቂቃ ይቀመጣሉ። ሲወጡ ይጠፋሉ። የAI ምክር መመሪያ እንጂ የተረጋገጠ ምስክር ወረቀት አይደለም።','Ergaawwan 40 dhumaa fi wixineen keessan caancala kana keessatti daqiiqaa 30 turu. Yeroo baatan ni haqamu. Gorsi AI qajeelfama malee ragaa mirkanaa’e miti.','ናይ መወዳእታ 40 መልእኽትታትን ረቂቕኩምን ኣብዚ ትር ን30 ደቒቓ ይቕመጡ። ምስ ወጻእኩም ይድምሰሱ። ምኽሪ AI መምርሒ እዩ፣ ዝተረጋገጸ ምስክር ኣይኮነን።','40-ka farriimood ee ugu dambeeya iyo qoraalkaaga waxay ku jiraan tab-kan 30 daqiiqo. Ka bixiddu way tirtirtaa. Talada AI waa hagid, ma aha shahaado la xaqiijiyay.'],
 coachApproval:['This request needs administrator approval. No action has been executed.','ጥያቄው የአስተዳዳሪ ፈቃድ ይፈልጋል። ምንም እርምጃ አልተወሰደም።','Gaaffiin kun hayyama bulchaa barbaada. Tarkaanfiin tokko illee hin raawwatamne.','እዚ ሕቶ ፍቓድ ኣመሓዳሪ የድልዮ። ዝተፈጸመ ስጉምቲ የለን።','Codsigan wuxuu u baahan yahay oggolaanshaha maamulaha. Wax tallaabo ah lama fulin.'],
 coachError:['Could not reach the career coach. Your question is saved below; you can send it again.','የሙያ አማካሪውን ማግኘት አልተቻለም። ጥያቄዎ ከታች ተቀምጧል፤ እንደገና መላክ ይችላሉ።','Gorsaa hojii bira ga’uun hin danda’amne. Gaaffiin keessan armaan gaditti jira; irra deebi’aa ergaa.','ኣማኻሪ ሞያ ክርከብ ኣይከኣለን። ሕቶኹም ኣብ ታሕቲ ተቐሚጡ ኣሎ፤ እንደገና ስደድዎ።','La taliyaha xirfadda lama gaari karin. Su’aashaadu hoos ayay ku kaydsan tahay; mar kale dir.'],
} as const
